exports.HANDLE_ERROR = 'HANDLE_ERROR';

exports.HANDLE_MESSAGE = 'HANDLE_MESSAGE';

exports.PROGRAM_CREATE = 'PROGRAM_CREATE';

exports.PROGRAM_INSTALL__START = 'PROGRAM_INSTALL__START';

exports.PROGRAM_INSTALL__STOP = 'PROGRAM_INSTALL__STOP';

exports.PROGRAM_INSTALL__STATUS = 'PROGRAM_INSTALL__STATUS';

exports.PROGRAM_RUN__START = 'PROGRAM_RUN__START';

exports.PROGRAM_RUN__STOP = 'PROGRAM_RUN__STOP';

exports.PROGRAM_RUN__STATUS = 'PROGRAM_RUN__STATUS';

exports.PROGRAM_BUILD__START = 'PROGRAM_BUILD__START';

exports.PROGRAM_BUILD__STOP = 'PROGRAM_BUILD__STOP';

exports.PROGRAM_BUILD__STATUS = 'PROGRAM_BUILD__STATUS';

exports.DIRECTORY_SELECT__START = 'DIRECTORY_SELECT__START';

exports.DIRECTORY_SELECT__DONE = 'DIRECTORY_SELECT__DONE';